version: '3'
services:
  location_service:
    env_file:
      - local.env
    build: location_service/
    volumes:
     - ./location_service:/code
     - /code/node_modules
    depends_on:
      - user_location_db
  user_location_db:
    image: "redis:alpine"

  user_service:
    env_file:
      - local.env
    build: user_service/
    volumes:
     - ./user_service:/code
     - /code/node_modules
    depends_on:
      - user_db
      - authentication_service
  user_db:
    image: "mongo:3.0.14"

  authentication_service:
    env_file:
      - local.env
    build: authentication_service/
    volumes:
     - ./authentication_service:/code
     - /code/node_modules
    depends_on:
      - authentication_db
  authentication_db:
    image: "mongo:3.0.14"

  proxy:
    build: proxy/
    ports:
     - "8080:8080"
     - "88:88"
    volumes:
     - ./proxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - location_service
      - authentication_service
      - user_service
